### ISSUE TITLE
Generate types in separate module

### ISSUE THREAD

**Issue by lorefnon** [JordanMarr/SqlHydra#24]
It would be nice if we could generate the Readers and row types in separate modules/files. 

My primary intent is to reuse the row types in a fable client.

**Comment by JordanMarr** [comment]
Thanks for the feedback. 

If I understand correctly, you want to put your generated types into the `Shared` project (assuming you are using a SAFE style template that creates `Client`, `Shared` and `Server` projects), and the readers into the `Server` project so that you can use the generated types as DTOs.

Personally, I only use the generated records for strongly typed data access, so I always map the data into custom domain objects or DTOs for use in my app. I would generally not want to have my database schema made directly available to the client for various reasons (tight coupling, inflexibility, etc). 

However, I am assuming your use case is for quick and easy CRUD style data? If so, I can definitely understand the appeal and convenience factor of such a design.

**Comment by lorefnon** [comment]
Yes, exactly. The app I am prototyping is (atleast yet) very simple and many of the entity types used in the API map 1:1 to the table row types, so I thought if I could just have the types generated in a separate module I could use the same on the client. 

While I have only used SqlHydra for an hr or so, love the DX so far - thanks for creating and open sourcing this library.

**Comment by JordanMarr** [comment]
You can actually have more than one .toml configuration file by specifying the name of the .toml file.

So in your server project, you can run a `Client` specific configuration and use relative pathing to save the file in your `Client` project. You will also want to select `No` on `Generate HydraReader`.
![image](https://user-images.githubusercontent.com/1030435/167704611-60a2de91-8a10-4d8f-af3f-ef7893df5d90.png)

Your server generated types will still create both types and readers. 
I'm not sure if you will be able to `select` your `Client` entities directly via `SqlHydra.Query` using the `Server` generated readers... 
If you can't do that, then you should be able to use [AutoMapper](https://github.com/AutoMapper/AutoMapper) to fairly easily translate from your `Server` entities to your `Client` entities in one-line of code and without any mapping required since the types would be identical.

**Comment by JordanMarr** [comment]
Actually you should be able to run the command like this (without the dashes):

`dotnet sqlhydra-sqlite "shared.toml"`

**Comment by lorefnon** [comment]
Ah, this is perfect - I missed out that I could already just prevent the readers from getting generated. Thanks a lot. 

> I'm not sure if you will be able to select your Client entities directly via SqlHydra.Query using the Server generated readers...

I don't think this is gonna be a problem, because the types are basically same I can conditionally open different modules eg.

```fsharp
#if FABLE_COMPILER
open Proj.Shared.DTO.``public``
#else
open Proj.Server.DAO.``public``
#endif
```

**Comment by JordanMarr** [comment]
One last thing:
After you run this it will automatically try to add `SharedTypes.fs` to your `Server.fsproj` file:

```F#
Compile Include="SharedTypes.fs">
    <Visible>False</Visible>
</Compile>
```

If you delete, it will just add it back every time, but if you change it to `None`, it will see that it exists and will not try to update it anymore.

```F#
<None Include="SharedTypes.fs">
  <Visible>False</Visible>
</None>
```

**Comment by lorefnon** [comment]
Umm, if these two are in different modules, then why do I need to care about this ? 

Is this primarily to prevent accidental usage or reduce build times ?

**Comment by JordanMarr** [comment]
Yes of course, you shouldn't have to worry about that as long as you put generate your toml files in separate projects.
