### ISSUE TITLE
sqlhydra-npgsql generation tool doesn't pick up "array" columns 

### ISSUE THREAD

**Issue by Swoorup** [JordanMarr/SqlHydra#37]
It appears that for schema like following:

```sql
create table draft_item
(
    topic     text        not null,
    id        text        not null,
    timestamp timestamptz not null,
    sequence  bigint      not null,
    payload   jsonb       not null,
    errors    text[]      not null,
    constraint pk_draft_items primary key (id, topic)
);
```

It simply skips over array type `errors`, generating the following:
```fsharp
    [<CLIMutable>]
    type draft_item =
        { topic: string
          id: string
          timestamp: System.DateTime
          sequence: int64
          [<SqlHydra.ProviderDbType("Jsonb")>]
          payload: string }
```

**Comment by JordanMarr** [comment]
SqlHydra supports the standard primitive parameter types. However, a few of the more specialized param types have been implemented by users (json, jsonb for npgsql), so I think the infrastructure should be in place to add support for more. 

You can see all the types that are supported for Npgsql here:
https://github.com/JordanMarr/SqlHydra/blob/main/src/SqlHydra.Npgsql/NpgsqlDataTypes.fs

Adding support for arrays would require the following changes:
- Adding a helper [Util](https://github.com/JordanMarr/SqlHydra/blob/ef191160eda0f609bb729d9f8f701590e068d72f/src/Tests/Npgsql/AdventureWorksNet6.fs#L32) function to load an array in the generated code 
- Adding a `text[]` mapping in NpgsqlDataTypes.fs that specifies above load function
- Adding a new table to the npgsql test .sql files that includes an array type for testing
- Adding an integration test

**Comment by EverybodyKurts** [comment]
Welp, I'm trying to implement this feature myself. However, after forking the repo and attempting to open the `src` directory using VS Code's remote dev container, I get the following build errors:

```bash
# error 1
No package oracle-database-preinstall-18c available.

# error 2
sed: can't read /etc/security/limits.d/oracle-database-preinstall-18c.conf: No such file or directory
```

I'm on an arm-based M1 Macbook Air. I've had trouble in the past building Docker containers because of my laptop's architecture.

**Comment by JordanMarr** [comment]
Oh no! Orace is such a pain.
TBH, I haven't used the vs code + remote dev containers setup in a long time. 
I just run `docker-compose up`. 

If you just want to do stuff with postgres, I think you could just do `docker-compose up postgresql`.

https://github.com/JordanMarr/SqlHydra/wiki/Contributing#using-visual-studio-or-rider

**Comment by kurt-mueller-osumc** [comment]
> provider db type to NpgsqlDbType.Array | NpgsqlDbType.Text (I think)

Is that a bitwise OR operator? In F#, it's `|||`.

![Screen Shot 2022-10-23 at 9 39 46 AM](https://user-images.githubusercontent.com/66080261/197395550-d5e898ca-0b4a-43cc-b2c8-8b4ca6d33110.png)

Currently running into a syntax error. I'll see if I can figure it out :D.

**Comment by kurt-mueller-osumc** [comment]
![Screen Shot 2022-10-23 at 9 41 52 AM](https://user-images.githubusercontent.com/66080261/197395656-19cea7e3-67c9-4e3f-832a-004b78e76d24.png)

Lol this works

**Comment by kurt-mueller-osumc** [comment]
> Adding a new table to the npgsql test .sql files that includes an array type for testing

Are you referring to: `./src/.devcontainer/postgresql/install.sql`?

**Comment by JordanMarr** [comment]
Yup, you just need to update install.sql and then rebuild:

### PostgreSQL: 
1) Add table to: `src/.devcontainer/postgresql/install.sql`
2) Run `docker-compose up --build postgresql` from the `src/.devcontainer` folder.

3) To update the Tests project, go to `src/Tests` folder and run:
```
dotnet run --project ..\SqlHydra.Npgsql --framework net6.0 -- sqlhydra-npgsql-net6.toml
```
(You can run the same for `net5.0` if you have it installed, or just skip that if you don't).

4) Add a few tests to exercise it.

**Comment by JordanMarr** [comment]
I started to implement this today, but it was (of course) much harder than I estimated.
Specifically because npgsql array params need to be specified with two flags:

```F#
p.NpgsqlDbType <- NpgsqlDbType.Text ||| NpgsqlDbType.Array
```

This property is actually set via reflection in SqlHydra.Query (to avoid needing provider specific version of SqlHydra.Query).

In the `NpgsqlDataTypes.fs` mappings file, a `ProviderDbType` `string option` value was specified for columns that would need a provider specific DbType to be set on the parameter. If the mappings `ProviderDbType` value was `Some`, a  `[<SqlHydra.ProviderDbType>]` attribute would be added to the generated record field. SqlHydra.Query would then check for this attribute when doing an insert or update and set the provider specific DbType property if found. 

However, since npgsql arrays require two fields, I had to refactor the mappings to take a `string list` instead of a `string option`. 
So generated array type columns will have two `[<SqlHydra.ProviderDbType>]` attributes, and the SqlHydra.Query library will need to generate a bitwise value to set to the DbType. 
I anticipate this will be tricky since I am creating the db type enums via reflection, but hopefully it will be possible.

**Comment by JordanMarr** [comment]
It looks like I made it way more complicated than I needed to.
Apparently I can parse `"Test,Array"` into a bitwise enum value:

```F#
let textArrayEnum = Enum.Parse(typeof<NpgsqlDbType>, "Text,Array") // succeeds
```

So I can leave my mappings model the same and pass in "Text,Array".

**Comment by JordanMarr** [comment]
SqlHydra.Npgsql [v1.0.4](https://www.nuget.org/packages/SqlHydra.Npgsql/) is released with support for text[] and integer[].

The change to the mappings ended up being fairly simple in the end:
https://github.com/JordanMarr/SqlHydra/blob/f0e2496c35e1f7c6a76573d005da688f8f039554/src/SqlHydra.Npgsql/NpgsqlDataTypes.fs#L50-L56
Please try it out!

**Comment by Swoorup** [comment]
Super thanks for this @JordanMarr . Will check it out and report if any issues. 👍🏼

**Comment by kurt-mueller-osumc** [comment]
Yes, thank you @JordanMarr!
