### ISSUE TITLE
Question: Can you exclude a column from being in a generated type?

### ISSUE THREAD

**Issue by Mousaka** [JordanMarr/SqlHydra#6]
We would like to add a created_at column to a table that our PostgresSQL that always gets set by our DB.
Is there a way to exclude this column when generating the type that represents this row, since we never use it in our program? The column is only used for debugging purposes.

**Comment by JordanMarr** [comment]
The filters currently accept:
- {table}
- {schema}/{table}

The ability to filter columns sounds useful. I think the filters could be augmented to allow this, but it would have to be fully qualified:
- {schema}/{table}/{column}


This is based on my assumption none of the other database providers allow nested schemas. 
if it turns out that any of them do, then it would would be better to use a different delimiter to indicate columns, such as:
- {schema}/{table}.{column}

In fact maybe that would be better anyway since it would also allow leaving off the schema:
- {table}.{column}

**Comment by Mousaka** [comment]
I see! thanks for answering.

We can of course work around this by setting a dummy value when creating the generated type before serializing it with the excludeColumn. But would prefer to not have that field :)

**Comment by JordanMarr** [comment]
Were you able to try out this change to see if it works for your scenario?

**Comment by JordanMarr** [comment]
Implemented in v0.610.0.
