### ISSUE TITLE
NoWarn 3391

### ISSUE THREAD

**Issue by RicoSaupeBosch** [JordanMarr/SqlHydra#97]
I am trying out the selectTask example exactly as in the documentation on a net8.0 console application. I am getting a warning which i cannot figure out. Am I missing something or do I really have to add nowarn? 

these are my references
```
<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
<PackageReference Include="SqlHydra.Query" Version="2.5.1" />
``` 

the warning

> This expression uses the implicit conversion 'static member ContextType.op_Implicit: createFn: (unit -> QueryContext) -> ContextType' 
 to convert type 'unit -> QueryContext' to type 'ContextType'. See https://aka.ms/fsharp-implicit-convs. This warning may be disabled using '#nowarn "3391".

![image](https://github.com/JordanMarr/SqlHydra/assets/83805528/6808138f-911a-4f57-85d6-9fbb0c68e4e4)

**Comment by JordanMarr** [comment]
Yes, F# now allows implicit conversion but you have to opt in by disabling the warning.
`selectAsync` and `selectTask` allow you to implicitly pass in an `openContext` function or a shared context`.

So, if you want the simpler, implicit context, you should add the `#nowarn` directive. 
Otherwise, you can explicitly wrap it in the ContextType discriminated union:

```F#
selectAsync HydraReader.Read (Create openContext) {
    for s in dbo.Systems do
    select s
}
```

**Comment by RicoSaupeBosch** [comment]
Thanks that was it. Could I have seen that in some documentation of yours? I may have overlooked it.

**Comment by JordanMarr** [comment]
No, that is not in the docs.
